### ISSUE TITLE
Does not work with Brave browser

### ISSUE THREAD

**Issue by wlai** [SelfControlApp/selfcontrol#613]
I've compared side-by-side Firefox, Chrome, and Brave Version 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit), and Brave doesn't work for a number of sites, including YouTube.

I've cleared browser cache. I've selected all the options in SelfControl including Block Common Subdomain, etc. My blacklist definitely contains the line: "youtube.com".  

I'm not sure what causes Brave's behavior, but do note that Brave is at an unknown state with DNS over HTTPS, which another issue suggests may be trigfering some compatibility issues: https://www.zdnet.com/article/dns-over-https-will-eventually-roll-out-in-all-major-browsers-despite-isp-opposition/

**Comment by ilMagnifico** [comment]
I use Brave too. Version 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)

I have had probably the same problem as you, please make sure you have added the website in this format:
http://www.twitch.tv OR www.twitch.tv and **not** as https://www.twitch.tv

I resolved in this way in the v2.x, don't ask me how it doesn't work with the HTTPS.

**Comment by cstigler** [comment]
Hi @wlai, are you still having this issue with version 3.0 (new upgrade out last week)?

I am generally not a Brave Browser user, but I just downloaded a copy to test this and ran a SelfControl block. On my copy, it's working fine (tested with several websites including `youtube.com`). I'm running macOS Catalina 10.15.3 and using Brave (with all default settings) `Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)`.

DoH will definitely break SelfControl, but luckily doesn't appear to be on in Brave yet (at least by default). That's an issue for another day :)

Closing for now, but please reopen if you think this is still an issue. If so, it sounds like it might be related to specific browser/system configurations so might be tough to track down.

**Comment by Fenwick17** [comment]
Just tested this myself on macOS Catalina 10.15.5 running Brave (default settings as far as im aware) `Version 1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)` and nothing in my blocklist is being blocked. When running self control if I then open Firefox or Chrome the sites are correctly showing as blocked

**Comment by rightisleft** [comment]
I'm still seeing this with about 30% of my blocked sites. 

(Note: Multi years user - Love the app!)
